#!/usr/bin/env bash

set -e

version=$(cat VERSION)
package='bam'

platforms=("linux/amd64" "linux/386" "darwin/amd64")

rm -rf release
mkdir -p release

for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    output_name=$package'-'v$version'-'$GOOS'-'$GOARCH

    env GOOS=$GOOS GOARCH=$GOARCH go build -o release/bam main.go
    pushd release
    tar -czvf $output_name.tar.gz bam
    popd
    rm release/bam
done
